/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import java.awt.Color;
import javax.swing.JFrame;

/**
 *
 * @author leito
 */
public class newLogin extends javax.swing.JFrame {

    /** Creates new form newLogin */
    public newLogin() {
         initComponents();

       
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        background = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        verProd = new javax.swing.JPanel();
        bttn2 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        verProd1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        bttn12 = new java.awt.Label();
        verProd2 = new javax.swing.JPanel();
        bttn13 = new java.awt.Label();
        jLabel12 = new javax.swing.JLabel();
        bttn14 = new java.awt.Label();
        jSeparator2 = new javax.swing.JSeparator();
        verProd3 = new javax.swing.JPanel();
        bttn15 = new java.awt.Label();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        bttn16 = new java.awt.Label();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, background, org.jdesktop.beansbinding.ELProperty.create("${enabled}"), this, org.jdesktop.beansbinding.BeanProperty.create("undecorated"));
        bindingGroup.addBinding(binding);

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));
        jPanel2.setLayout(new java.awt.CardLayout());
        background.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 760, 160));

        menu.setBackground(new java.awt.Color(0, 51, 153));

        verProd.setBackground(new java.awt.Color(0, 80, 160));
        verProd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        verProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                verProdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                verProdMouseExited(evt);
            }
        });

        bttn2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bttn2.setForeground(new java.awt.Color(255, 255, 255));
        bttn2.setName(""); // NOI18N
        bttn2.setText("Ver Productos");
        bttn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bttn2MouseEntered(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/outline_local_grocery_store_white_18dp_1.png"))); // NOI18N

        javax.swing.GroupLayout verProdLayout = new javax.swing.GroupLayout(verProd);
        verProd.setLayout(verProdLayout);
        verProdLayout.setHorizontalGroup(
            verProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, verProdLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addComponent(bttn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        verProdLayout.setVerticalGroup(
            verProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verProdLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(verProdLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(bttn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(20, 70, 160));
        jPanel5.setLayout(new java.awt.BorderLayout());

        verProd1.setBackground(new java.awt.Color(0, 80, 160));
        verProd1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        verProd1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                verProd1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                verProd1MouseExited(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/outline_people_white_18dp.png"))); // NOI18N

        bttn12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bttn12.setForeground(new java.awt.Color(255, 255, 255));
        bttn12.setName(""); // NOI18N
        bttn12.setText("Ver Usuarios");
        bttn12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bttn12MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout verProd1Layout = new javax.swing.GroupLayout(verProd1);
        verProd1.setLayout(verProd1Layout);
        verProd1Layout.setHorizontalGroup(
            verProd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, verProd1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel11)
                .addGap(48, 48, 48)
                .addComponent(bttn12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        verProd1Layout.setVerticalGroup(
            verProd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verProd1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(verProd1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(bttn12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        verProd2.setBackground(new java.awt.Color(0, 80, 160));
        verProd2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        verProd2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                verProd2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                verProd2MouseExited(evt);
            }
        });

        bttn13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bttn13.setForeground(new java.awt.Color(255, 255, 255));
        bttn13.setName(""); // NOI18N
        bttn13.setText("Ver Proveedores");
        bttn13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bttn13MouseEntered(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/outline_person_pin_white_18dp.png"))); // NOI18N

        javax.swing.GroupLayout verProd2Layout = new javax.swing.GroupLayout(verProd2);
        verProd2.setLayout(verProd2Layout);
        verProd2Layout.setHorizontalGroup(
            verProd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, verProd2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel12)
                .addGap(48, 48, 48)
                .addComponent(bttn13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        verProd2Layout.setVerticalGroup(
            verProd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verProd2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(verProd2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(bttn13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        bttn14.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bttn14.setForeground(new java.awt.Color(255, 255, 255));
        bttn14.setName(""); // NOI18N
        bttn14.setText("Constructores 3000 C.A");

        verProd3.setBackground(new java.awt.Color(0, 80, 160));
        verProd3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        verProd3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                verProd3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                verProd3MouseExited(evt);
            }
        });

        bttn15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bttn15.setForeground(new java.awt.Color(255, 255, 255));
        bttn15.setName(""); // NOI18N
        bttn15.setText("Ver Estadisticas");
        bttn15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bttn15MouseEntered(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/outline_assessment_white_18dp.png"))); // NOI18N
        jLabel13.setToolTipText("");

        javax.swing.GroupLayout verProd3Layout = new javax.swing.GroupLayout(verProd3);
        verProd3.setLayout(verProd3Layout);
        verProd3Layout.setHorizontalGroup(
            verProd3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, verProd3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel13)
                .addGap(48, 48, 48)
                .addComponent(bttn15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        verProd3Layout.setVerticalGroup(
            verProd3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verProd3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(verProd3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(bttn15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel14.setToolTipText("");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8_Sign_Out_50px.png"))); // NOI18N
        jLabel15.setToolTipText("");

        bttn16.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bttn16.setForeground(new java.awt.Color(255, 255, 255));
        bttn16.setName(""); // NOI18N
        bttn16.setText("Cerrar Sesion");

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(299, 299, 299))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator2)
                    .addComponent(bttn14, javax.swing.GroupLayout.PREFERRED_SIZE, 206, Short.MAX_VALUE))
                .addGap(53, 53, 53))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(verProd2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(verProd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(verProd1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(verProd3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addComponent(bttn16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15))
                    .addComponent(jLabel14))
                .addGap(34, 34, 34))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(bttn14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addComponent(verProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(verProd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(verProd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0)
                .addComponent(verProd3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(183, 183, 183)
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addGap(5, 5, 5)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(bttn16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        background.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 700));

        jLabel2.setBackground(new java.awt.Color(153, 153, 153));
        jLabel2.setForeground(new java.awt.Color(102, 255, 102));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/baseline_cancel_black_18dp.png"))); // NOI18N
        jLabel2.setToolTipText("");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        background.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 10, -1, -1));

        tabla.setAutoCreateRowSorter(true);
        tabla.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tipo", "Nombre", "Precio", "Proveedor", "Objeto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        background.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 640, 320));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 700));

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void verProdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verProdMouseEntered
        verProd.setBackground(new java.awt.Color(30, 120, 180));
        bttn2.setBackground(new java.awt.Color(30, 120, 180));
    }//GEN-LAST:event_verProdMouseEntered

    private void verProdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verProdMouseExited
        verProd.setBackground(new java.awt.Color(0, 80, 160));
        bttn2.setBackground(new java.awt.Color(0, 80, 160));
    }//GEN-LAST:event_verProdMouseExited

    private void verProd1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verProd1MouseEntered
        // TODO add your handling code here:  verProd1
        verProd1.setBackground(new java.awt.Color(30, 120, 180));
        bttn12.setBackground(new java.awt.Color(30, 120, 180));        
    }//GEN-LAST:event_verProd1MouseEntered

    private void verProd1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verProd1MouseExited
        // TODO add your handling code here:
        verProd1.setBackground(new java.awt.Color(0, 80, 160));
        bttn12.setBackground(new java.awt.Color(0, 80, 160));       
    }//GEN-LAST:event_verProd1MouseExited

    private void bttn2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttn2MouseEntered
        verProd.setBackground(new java.awt.Color(30, 120, 180));
        bttn2.setBackground(new java.awt.Color(30, 120, 180));    
    }//GEN-LAST:event_bttn2MouseEntered

    private void bttn12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttn12MouseEntered
        verProd1.setBackground(new java.awt.Color(30, 120, 180));
        bttn12.setBackground(new java.awt.Color(30, 120, 180));  
    }//GEN-LAST:event_bttn12MouseEntered

    private void verProd2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verProd2MouseEntered
        verProd2.setBackground(new java.awt.Color(30, 120, 180));
        bttn13.setBackground(new java.awt.Color(30, 120, 180));
    }//GEN-LAST:event_verProd2MouseEntered

    private void verProd2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verProd2MouseExited
        verProd2.setBackground(new java.awt.Color(0, 80, 160));
        bttn13.setBackground(new java.awt.Color(0, 80, 160));
    }//GEN-LAST:event_verProd2MouseExited

    private void bttn13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttn13MouseEntered
       verProd2.setBackground(new java.awt.Color(30, 120, 180));
       bttn13.setBackground(new java.awt.Color(30, 120, 180));
       //bttn13
    }//GEN-LAST:event_bttn13MouseEntered

    private void bttn15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttn15MouseEntered
       verProd3.setBackground(new java.awt.Color(30, 120, 180));
       bttn15.setBackground(new java.awt.Color(30, 120, 180));
    }//GEN-LAST:event_bttn15MouseEntered

    private void verProd3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verProd3MouseEntered
       verProd3.setBackground(new java.awt.Color(30, 120, 180));
       bttn15.setBackground(new java.awt.Color(30, 120, 180));
    }//GEN-LAST:event_verProd3MouseEntered

    private void verProd3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verProd3MouseExited
        verProd3.setBackground(new java.awt.Color(0, 80, 160));
        bttn15.setBackground(new java.awt.Color(0, 80, 160));
    }//GEN-LAST:event_verProd3MouseExited

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
       System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
       jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/outline_close_black_18dp.png"))); 
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
      jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/baseline_cancel_black_18dp.png"))); //baseline_cancel_black_18dp
    }//GEN-LAST:event_jLabel2MouseExited

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_tablaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private java.awt.Label bttn12;
    private java.awt.Label bttn13;
    private java.awt.Label bttn14;
    private java.awt.Label bttn15;
    private java.awt.Label bttn16;
    private java.awt.Label bttn2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel menu;
    private javax.swing.JTable tabla;
    private javax.swing.JPanel verProd;
    private javax.swing.JPanel verProd1;
    private javax.swing.JPanel verProd2;
    private javax.swing.JPanel verProd3;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
