/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import Control.controlTablas;
import Control.controlador;
import Estructuras.Producto;
import Estructuras.Usuario;
import Estructuras.listaProd;
import controlXml.controlXmlProd;
import javax.swing.JFrame;
import java.awt.Point;
import static java.awt.SystemColor.control;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author leito
 */
public class newVistaProducto extends javax.swing.JFrame {
private Point currentLocation;
int i,j;
controlTablas control;
listaProd cosas;
Usuario currentUser;
controlXmlProd xml= new controlXmlProd();
vistaAddProd vent;
//controlXml xml=new controlXml();
ArrayList<Producto> objeto;
boolean activados;
    /** Creates new form newLogin */
    public newVistaProducto() {
         initComponents();
         verProd5.requestFocus();       
    }
    public newVistaProducto(Usuario currentUser){
        initComponents();
        control = new controlTablas(tabla, this);
        this.currentUser = currentUser;
        objeto = xml.todasLosUser();
        cosas = new listaProd(objeto);
        //control.activa_Desactiva(false);
        verProd5.requestFocus(); 
         if (!cosas.existeProd()) {
            activados= true;
        }
        else {
            //control.activa_Desactiva(false);        
            verProd4.setBackground(new java.awt.Color(192,192,192));
            verProd6.setBackground(new java.awt.Color(192,192,192));
            verProd7.setBackground(new java.awt.Color(192,192,192));
            activados= false;
        }
        control.llenarTablaProd(this.cosas,tabla);
        if (tabla.getColumnModel().getColumnCount() > 0) {
            tabla.getColumnModel().getColumn(6).setMinWidth(0);
            tabla.getColumnModel().getColumn(6).setPreferredWidth(0);
            tabla.getColumnModel().getColumn(6).setMaxWidth(0);
        }
        
    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        background = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        verProd = new javax.swing.JPanel();
        bttn2 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        verProd1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        bttn12 = new java.awt.Label();
        verProd2 = new javax.swing.JPanel();
        bttn13 = new java.awt.Label();
        jLabel12 = new javax.swing.JLabel();
        verProd3 = new javax.swing.JPanel();
        bttn15 = new java.awt.Label();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        bttn16 = new java.awt.Label();
        jPanel2 = new javax.swing.JPanel();
        bttn17 = new java.awt.Label();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        bttn14 = new java.awt.Label();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        verProd4 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        verProd5 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        verProd7 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        verProd6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, background, org.jdesktop.beansbinding.ELProperty.create("${enabled}"), this, org.jdesktop.beansbinding.BeanProperty.create("undecorated"));
        bindingGroup.addBinding(binding);

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                backgroundMouseDragged(evt);
            }
        });
        background.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backgroundMouseClicked(evt);
            }
        });
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu.setBackground(new java.awt.Color(0, 51, 153));

        verProd.setBackground(new java.awt.Color(0, 153, 204));
        verProd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        verProd.setNextFocusableComponent(verProd1);
        verProd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                verProdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                verProdFocusLost(evt);
            }
        });
        verProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                verProdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                verProdMouseExited(evt);
            }
        });

        bttn2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bttn2.setForeground(new java.awt.Color(255, 255, 255));
        bttn2.setName(""); // NOI18N
        bttn2.setText("Ver Productos");
        bttn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bttn2MouseEntered(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/outline_local_grocery_store_white_18dp_1.png"))); // NOI18N

        javax.swing.GroupLayout verProdLayout = new javax.swing.GroupLayout(verProd);
        verProd.setLayout(verProdLayout);
        verProdLayout.setHorizontalGroup(
            verProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, verProdLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addComponent(bttn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        verProdLayout.setVerticalGroup(
            verProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verProdLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(verProdLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(bttn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(20, 70, 160));
        jPanel5.setLayout(new java.awt.BorderLayout());

        verProd1.setBackground(new java.awt.Color(0, 80, 160));
        verProd1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        verProd1.setNextFocusableComponent(verProd2);
        verProd1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                verProd1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                verProd1FocusLost(evt);
            }
        });
        verProd1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verProd1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                verProd1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                verProd1MouseExited(evt);
            }
        });
        verProd1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                verProd1KeyPressed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/outline_people_white_18dp.png"))); // NOI18N

        bttn12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bttn12.setForeground(new java.awt.Color(255, 255, 255));
        bttn12.setName(""); // NOI18N
        bttn12.setText("Ver Usuarios");
        bttn12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttn12MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bttn12MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout verProd1Layout = new javax.swing.GroupLayout(verProd1);
        verProd1.setLayout(verProd1Layout);
        verProd1Layout.setHorizontalGroup(
            verProd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, verProd1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel11)
                .addGap(48, 48, 48)
                .addComponent(bttn12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        verProd1Layout.setVerticalGroup(
            verProd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verProd1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(verProd1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(bttn12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        verProd2.setBackground(new java.awt.Color(0, 80, 160));
        verProd2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        verProd2.setNextFocusableComponent(verProd3);
        verProd2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                verProd2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                verProd2FocusLost(evt);
            }
        });
        verProd2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verProd2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                verProd2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                verProd2MouseExited(evt);
            }
        });
        verProd2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                verProd2KeyPressed(evt);
            }
        });

        bttn13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bttn13.setForeground(new java.awt.Color(255, 255, 255));
        bttn13.setName(""); // NOI18N
        bttn13.setText("Ver Proveedores");
        bttn13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttn13MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bttn13MouseEntered(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/outline_person_pin_white_18dp.png"))); // NOI18N

        javax.swing.GroupLayout verProd2Layout = new javax.swing.GroupLayout(verProd2);
        verProd2.setLayout(verProd2Layout);
        verProd2Layout.setHorizontalGroup(
            verProd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, verProd2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel12)
                .addGap(48, 48, 48)
                .addComponent(bttn13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        verProd2Layout.setVerticalGroup(
            verProd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verProd2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(verProd2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(bttn13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        verProd3.setBackground(new java.awt.Color(0, 80, 160));
        verProd3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        verProd3.setNextFocusableComponent(jLabel15);
        verProd3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                verProd3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                verProd3FocusLost(evt);
            }
        });
        verProd3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                verProd3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                verProd3MouseExited(evt);
            }
        });

        bttn15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bttn15.setForeground(new java.awt.Color(255, 255, 255));
        bttn15.setName(""); // NOI18N
        bttn15.setText("Ver Estadisticas");
        bttn15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bttn15MouseEntered(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/outline_assessment_white_18dp.png"))); // NOI18N
        jLabel13.setToolTipText("");

        javax.swing.GroupLayout verProd3Layout = new javax.swing.GroupLayout(verProd3);
        verProd3.setLayout(verProd3Layout);
        verProd3Layout.setHorizontalGroup(
            verProd3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, verProd3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel13)
                .addGap(48, 48, 48)
                .addComponent(bttn15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        verProd3Layout.setVerticalGroup(
            verProd3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verProd3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(verProd3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(bttn15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel14.setToolTipText("");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8_Sign_Out_30px.png"))); // NOI18N
        jLabel15.setToolTipText("");
        jLabel15.setNextFocusableComponent(verProd5);
        jLabel15.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel15FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jLabel15FocusLost(evt);
            }
        });
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel15MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel15MouseExited(evt);
            }
        });

        bttn16.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bttn16.setForeground(new java.awt.Color(255, 255, 255));
        bttn16.setName(""); // NOI18N
        bttn16.setText("Cerrar Sesion");
        bttn16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttn16MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bttn16MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bttn16MouseExited(evt);
            }
        });
        bttn16.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                bttn16FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                bttn16FocusLost(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(299, 299, 299))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                        .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(verProd2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(verProd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(verProd1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(verProd3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                        .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(menuLayout.createSequentialGroup()
                                .addComponent(bttn16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15))
                            .addComponent(jLabel14))
                        .addGap(34, 34, 34))))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addComponent(verProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(verProd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(verProd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0)
                .addComponent(verProd3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                .addGap(5, 5, 5)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(bttn16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        background.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 300, 650));

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));

        bttn17.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        bttn17.setForeground(new java.awt.Color(255, 255, 255));
        bttn17.setName(""); // NOI18N
        bttn17.setText("Inventario de Productos");
        bttn17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bttn17MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bttn17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(340, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bttn17, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        background.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 760, 90));

        jLabel2.setBackground(new java.awt.Color(153, 153, 153));
        jLabel2.setForeground(new java.awt.Color(102, 255, 102));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/baseline_cancel_black_18dp.png"))); // NOI18N
        jLabel2.setToolTipText("");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        background.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 10, -1, -1));

        tabla.setAutoCreateRowSorter(true);
        tabla.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tipo", "Nombre", "Precio", "Proveedor", "Objeto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.setGridColor(new java.awt.Color(255, 255, 255));
        tabla.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);
        if (tabla.getColumnModel().getColumnCount() > 0) {
            tabla.getColumnModel().getColumn(4).setMinWidth(0);
            tabla.getColumnModel().getColumn(4).setPreferredWidth(0);
            tabla.getColumnModel().getColumn(4).setMaxWidth(0);
        }

        background.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 640, 460));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        bttn14.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bttn14.setForeground(new java.awt.Color(0, 51, 153));
        bttn14.setName(""); // NOI18N
        bttn14.setText("Constructores 3000 C.A");
        bttn14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bttn14MousePressed(evt);
            }
        });
        bttn14.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                bttn14MouseDragged(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(0, 51, 153));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/minimze2.png"))); // NOI18N
        jLabel16.setToolTipText("");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel16MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel16MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bttn14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 742, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(63, 63, 63))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bttn14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        background.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 50));

        verProd4.setBackground(new java.awt.Color(0, 80, 160));
        verProd4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        verProd4.setNextFocusableComponent(verProd);
        verProd4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                verProd4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                verProd4FocusLost(evt);
            }
        });
        verProd4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                verProd4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                verProd4MouseExited(evt);
            }
        });
        verProd4.setLayout(null);

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8_Trash_Can_25px.png"))); // NOI18N
        jLabel17.setText("Eliminar");
        jLabel17.setToolTipText("");
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel17MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel17MouseExited(evt);
            }
        });
        verProd4.add(jLabel17);
        jLabel17.setBounds(10, 0, 100, 40);

        background.add(verProd4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 630, 120, 40));

        verProd5.setBackground(new java.awt.Color(0, 80, 160));
        verProd5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        verProd5.setNextFocusableComponent(verProd6);
        verProd5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                verProd5FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                verProd5FocusLost(evt);
            }
        });
        verProd5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                verProd5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                verProd5MouseExited(evt);
            }
        });
        verProd5.setLayout(null);

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8_Add_25px.png"))); // NOI18N
        jLabel18.setText("Agregar");
        jLabel18.setToolTipText("");
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel18MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel18MouseExited(evt);
            }
        });
        verProd5.add(jLabel18);
        jLabel18.setBounds(10, 0, 100, 40);

        background.add(verProd5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 630, 120, 40));

        verProd7.setBackground(new java.awt.Color(0, 80, 160));
        verProd7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        verProd7.setNextFocusableComponent(verProd4);
        verProd7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                verProd7FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                verProd7FocusLost(evt);
            }
        });
        verProd7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                verProd7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                verProd7MouseExited(evt);
            }
        });
        verProd7.setLayout(null);

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8_Edit_25px.png"))); // NOI18N
        jLabel20.setText("Comprar/Vender");
        jLabel20.setToolTipText("");
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel20MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel20MouseExited(evt);
            }
        });
        verProd7.add(jLabel20);
        jLabel20.setBounds(10, 0, 150, 40);

        background.add(verProd7, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 630, 170, 40));

        verProd6.setBackground(new java.awt.Color(0, 80, 160));
        verProd6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        verProd6.setNextFocusableComponent(verProd4);
        verProd6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                verProd6FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                verProd6FocusLost(evt);
            }
        });
        verProd6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                verProd6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                verProd6MouseExited(evt);
            }
        });
        verProd6.setLayout(null);

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8_Edit_25px.png"))); // NOI18N
        jLabel19.setText("Modificar");
        jLabel19.setToolTipText("");
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel19MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel19MouseExited(evt);
            }
        });
        verProd6.add(jLabel19);
        jLabel19.setBounds(10, 0, 100, 40);

        background.add(verProd6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 630, 120, 40));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 700));

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void verProdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verProdMouseEntered
        verProd.setBackground(new java.awt.Color(30, 120, 180));
        bttn2.setBackground(new java.awt.Color(30, 120, 180));
    }//GEN-LAST:event_verProdMouseEntered

    private void verProdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verProdMouseExited
        verProd.setBackground(new java.awt.Color(0, 153, 204));
        bttn2.setBackground(new java.awt.Color(0, 153, 204));
    }//GEN-LAST:event_verProdMouseExited

    private void verProd1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verProd1MouseEntered
        // TODO add your handling code here:  verProd1
        verProd1.setBackground(new java.awt.Color(30, 120, 180));
        bttn12.setBackground(new java.awt.Color(30, 120, 180));        
    }//GEN-LAST:event_verProd1MouseEntered

    private void verProd1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verProd1MouseExited
        // TODO add your handling code here:
        verProd1.setBackground(new java.awt.Color(0, 80, 160));
        bttn12.setBackground(new java.awt.Color(0, 80, 160));       
    }//GEN-LAST:event_verProd1MouseExited

    private void bttn2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttn2MouseEntered
        verProd.setBackground(new java.awt.Color(30, 120, 180));
        bttn2.setBackground(new java.awt.Color(30, 120, 180));    
    }//GEN-LAST:event_bttn2MouseEntered

    private void bttn12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttn12MouseEntered
        verProd1.setBackground(new java.awt.Color(30, 120, 180));
        bttn12.setBackground(new java.awt.Color(30, 120, 180));  
    }//GEN-LAST:event_bttn12MouseEntered

    private void verProd2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verProd2MouseEntered
        verProd2.setBackground(new java.awt.Color(30, 120, 180));
        bttn13.setBackground(new java.awt.Color(30, 120, 180));
    }//GEN-LAST:event_verProd2MouseEntered

    private void verProd2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verProd2MouseExited
        verProd2.setBackground(new java.awt.Color(0, 80, 160));
        bttn13.setBackground(new java.awt.Color(0, 80, 160));
    }//GEN-LAST:event_verProd2MouseExited

    private void bttn13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttn13MouseEntered
       verProd2.setBackground(new java.awt.Color(30, 120, 180));
       bttn13.setBackground(new java.awt.Color(30, 120, 180));
       //bttn13
    }//GEN-LAST:event_bttn13MouseEntered

    private void bttn15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttn15MouseEntered
       verProd3.setBackground(new java.awt.Color(30, 120, 180));
       bttn15.setBackground(new java.awt.Color(30, 120, 180));
    }//GEN-LAST:event_bttn15MouseEntered

    private void verProd3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verProd3MouseEntered
       verProd3.setBackground(new java.awt.Color(30, 120, 180));
       bttn15.setBackground(new java.awt.Color(30, 120, 180));
    }//GEN-LAST:event_verProd3MouseEntered

    private void verProd3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verProd3MouseExited
        verProd3.setBackground(new java.awt.Color(0, 80, 160));
        bttn15.setBackground(new java.awt.Color(0, 80, 160));
    }//GEN-LAST:event_verProd3MouseExited

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
       System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
       jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/twotone_cancel_black_18dp.png"))); 
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
      jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/baseline_cancel_black_18dp.png"))); //baseline_cancel_black_18dp
    }//GEN-LAST:event_jLabel2MouseExited

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_tablaMouseClicked

    private void bttn17MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttn17MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_bttn17MouseEntered

    private void backgroundMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundMouseDragged
//                    int a = evt.getXOnScreen()-this.i;
//                    int b = evt.getYOnScreen()-this.j;
//                    this.setLocation(a,b);      

    }//GEN-LAST:event_backgroundMouseDragged

    private void backgroundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundMouseClicked
//        Point currentScreenLocation = evt.getLocationOnScreen();
//        this.setLocation(currentScreenLocation.x - currentLocation.x, currentScreenLocation.y - currentLocation.y);
    }//GEN-LAST:event_backgroundMouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked

    }//GEN-LAST:event_jPanel1MouseClicked

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int cI = evt.getXOnScreen();
        int cJ= evt.getYOnScreen();
        this.setLocation(cI-i,cJ-j);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        i = evt.getX();
        j= evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void bttn14MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttn14MousePressed
        i = evt.getX();
        j= evt.getY();
    }//GEN-LAST:event_bttn14MousePressed

    private void bttn14MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttn14MouseDragged
        int cI = evt.getXOnScreen();
        int cJ= evt.getYOnScreen();
        this.setLocation(cI-i,cJ-j);
    }//GEN-LAST:event_bttn14MouseDragged

    private void verProd4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verProd4MouseEntered
       verProd4.setBackground(new java.awt.Color(30, 120, 180));       
    }//GEN-LAST:event_verProd4MouseEntered

    private void verProd4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verProd4MouseExited
        verProd4.setBackground(new java.awt.Color(0, 80, 160));  
    }//GEN-LAST:event_verProd4MouseExited

    private void jLabel16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseEntered
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/minimze3.png"))); 
    }//GEN-LAST:event_jLabel16MouseEntered

    private void jLabel16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseExited
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/minimze2.png"))); 
    }//GEN-LAST:event_jLabel16MouseExited

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
       this.setState(newVistaProducto.ICONIFIED);
    }//GEN-LAST:event_jLabel16MouseClicked

    private void verProd5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verProd5MouseEntered
       verProd5.setBackground(new java.awt.Color(30, 120, 180));      
    }//GEN-LAST:event_verProd5MouseEntered

    private void verProd5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verProd5MouseExited
       verProd5.setBackground(new java.awt.Color(0, 80, 160));       
    }//GEN-LAST:event_verProd5MouseExited

    private void verProd6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verProd6MouseEntered
        verProd6.setBackground(new java.awt.Color(30, 120, 180));
    }//GEN-LAST:event_verProd6MouseEntered

    private void verProd6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verProd6MouseExited
        verProd6.setBackground(new java.awt.Color(0, 80, 160));
    }//GEN-LAST:event_verProd6MouseExited

    private void jLabel17MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseEntered
       verProd4.setBackground(new java.awt.Color(30, 120, 180));  
    }//GEN-LAST:event_jLabel17MouseEntered

    private void jLabel17MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseExited
        verProd4.setBackground(new java.awt.Color(0, 80, 160));  
    }//GEN-LAST:event_jLabel17MouseExited

    private void jLabel19MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseEntered
       verProd6.setBackground(new java.awt.Color(30, 120, 180));
    }//GEN-LAST:event_jLabel19MouseEntered

    private void jLabel19MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseExited
       verProd6.setBackground(new java.awt.Color(0, 80, 160));
    }//GEN-LAST:event_jLabel19MouseExited

    private void jLabel18MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseEntered
         verProd5.setBackground(new java.awt.Color(30, 120, 180));   
    }//GEN-LAST:event_jLabel18MouseEntered

    private void jLabel18MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseExited
         verProd5.setBackground(new java.awt.Color(0, 80, 160));   
    }//GEN-LAST:event_jLabel18MouseExited

    private void verProdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_verProdFocusGained
        verProd.setBackground(new java.awt.Color(30, 120, 180));
        bttn2.setBackground(new java.awt.Color(30, 120, 180));
    }//GEN-LAST:event_verProdFocusGained

    private void verProdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_verProdFocusLost
        verProd.setBackground(new java.awt.Color(0,153,204)); 
        bttn2.setBackground(new java.awt.Color(0, 153, 204));
    }//GEN-LAST:event_verProdFocusLost

    private void verProd5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_verProd5FocusGained
        verProd5.setBackground(new java.awt.Color(30, 120, 180));  
    }//GEN-LAST:event_verProd5FocusGained

    private void verProd5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_verProd5FocusLost
        verProd5.setBackground(new java.awt.Color(0,80,160));
    }//GEN-LAST:event_verProd5FocusLost

    private void verProd6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_verProd6FocusGained
        verProd6.setBackground(new java.awt.Color(30, 120, 180));  
    }//GEN-LAST:event_verProd6FocusGained

    private void verProd6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_verProd6FocusLost
        verProd6.setBackground(new java.awt.Color(0,80,160));
    }//GEN-LAST:event_verProd6FocusLost

    private void verProd4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_verProd4FocusGained
        verProd4.setBackground(new java.awt.Color(30, 120, 180)); 
    }//GEN-LAST:event_verProd4FocusGained

    private void verProd4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_verProd4FocusLost
        verProd4.setBackground(new java.awt.Color(0,80,160));
    }//GEN-LAST:event_verProd4FocusLost

    private void verProd1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_verProd1FocusGained
        verProd1.setBackground(new java.awt.Color(30, 120, 180));
        bttn12.setBackground(new java.awt.Color(30, 120, 180));    
    }//GEN-LAST:event_verProd1FocusGained

    private void verProd1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_verProd1FocusLost
        verProd1.setBackground(new java.awt.Color(0, 80, 160));
        bttn12.setBackground(new java.awt.Color(0, 80, 160));    
    }//GEN-LAST:event_verProd1FocusLost

    private void verProd2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_verProd2FocusGained
        verProd2.setBackground(new java.awt.Color(30, 120, 180));
        bttn13.setBackground(new java.awt.Color(30, 120, 180));
    }//GEN-LAST:event_verProd2FocusGained

    private void verProd2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_verProd2FocusLost
        verProd2.setBackground(new java.awt.Color(0, 80, 160));
        bttn13.setBackground(new java.awt.Color(0, 80, 160));
    }//GEN-LAST:event_verProd2FocusLost

    private void bttn16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttn16MouseEntered
        bttn16.setForeground(new java.awt.Color(192, 192, 192));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8_Sign_Out_30px_1.png"))); 
    }//GEN-LAST:event_bttn16MouseEntered

    private void bttn16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttn16MouseExited
        bttn16.setForeground(new java.awt.Color(255,255,255));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8_Sign_Out_30px.png"))); 
    }//GEN-LAST:event_bttn16MouseExited

    private void bttn16FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bttn16FocusGained
        bttn16.setForeground(new java.awt.Color(192, 192, 192));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8_Sign_Out_30px_1.png"))); 
    }//GEN-LAST:event_bttn16FocusGained

    private void bttn16FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bttn16FocusLost
        bttn16.setForeground(new java.awt.Color(255,255,255));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8_Sign_Out_30px.png"))); 
    }//GEN-LAST:event_bttn16FocusLost

    private void jLabel15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseEntered
        bttn16.setForeground(new java.awt.Color(192, 192, 192));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8_Sign_Out_30px_1.png"))); 
    }//GEN-LAST:event_jLabel15MouseEntered

    private void jLabel15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseExited
        bttn16.setForeground(new java.awt.Color(255,255,255));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8_Sign_Out_30px.png"))); 
    }//GEN-LAST:event_jLabel15MouseExited

    private void jLabel15FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel15FocusGained
        bttn16.setForeground(new java.awt.Color(192, 192, 192));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8_Sign_Out_30px_1.png"))); 
    }//GEN-LAST:event_jLabel15FocusGained

    private void jLabel15FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel15FocusLost
        bttn16.setForeground(new java.awt.Color(255,255,255));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/icons8_Sign_Out_30px.png"))); 
    }//GEN-LAST:event_jLabel15FocusLost

    private void verProd3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_verProd3FocusGained
       verProd3.setBackground(new java.awt.Color(30, 120, 180));
       bttn15.setBackground(new java.awt.Color(30, 120, 180));
    }//GEN-LAST:event_verProd3FocusGained

    private void verProd3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_verProd3FocusLost
        verProd3.setBackground(new java.awt.Color(0, 80, 160));
        bttn15.setBackground(new java.awt.Color(0, 80, 160));
    }//GEN-LAST:event_verProd3FocusLost

    private void bttn16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttn16MouseClicked
       controlador next= new controlador(this);
       next.activaVentana(new VistaLogin(),this );
    }//GEN-LAST:event_bttn16MouseClicked

    private void verProd1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verProd1MouseClicked
        control.activaVentana(new admVistaUser(currentUser), this);     
    }//GEN-LAST:event_verProd1MouseClicked

    private void bttn12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttn12MouseClicked
        control.activaVentana(new admVistaUser(currentUser), this);     
    }//GEN-LAST:event_bttn12MouseClicked

    private void verProd1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_verProd1KeyPressed
        if(evt.getKeyCode()==(KeyEvent.VK_ENTER)){
        control.activaVentana(new admVistaUser(currentUser), this);               
        }
    }//GEN-LAST:event_verProd1KeyPressed

    private void verProd2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verProd2MouseClicked
        control.activaVentana(new admVistaProv(currentUser), this);
    }//GEN-LAST:event_verProd2MouseClicked

    private void verProd2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_verProd2KeyPressed
       control.activaVentana(new admVistaProv(currentUser), this);
    }//GEN-LAST:event_verProd2KeyPressed

    private void bttn13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttn13MouseClicked
        control.activaVentana(new admVistaProv(currentUser), this);
    }//GEN-LAST:event_bttn13MouseClicked
       control.activaVentana(new admVistaUser(currentUser), this);
    }//GEN-LAST:event_verProd1MouseClicked

    private void bttn12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttn12MouseClicked
        control.activaVentana(new admVistaUser(currentUser), this);
    }//GEN-LAST:event_bttn12MouseClicked

    private void verProd1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_verProd1KeyPressed
        control.activaVentana(new admVistaUser(currentUser), this);
    }//GEN-LAST:event_verProd1KeyPressed

    private void jLabel20MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseEntered
        verProd7.setBackground(new java.awt.Color(30, 120, 180));  
    }//GEN-LAST:event_jLabel20MouseEntered

    private void jLabel20MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseExited
        verProd7.setBackground(new java.awt.Color(0, 80, 160));  
    }//GEN-LAST:event_jLabel20MouseExited

    private void verProd7FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_verProd7FocusGained
        verProd7.setBackground(new java.awt.Color(30, 120, 180)); 
    }//GEN-LAST:event_verProd7FocusGained

    private void verProd7FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_verProd7FocusLost
        verProd7.setBackground(new java.awt.Color(0,80,160));
    }//GEN-LAST:event_verProd7FocusLost

    private void verProd7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verProd7MouseEntered
        verProd7.setBackground(new java.awt.Color(30, 120, 180));       
    }//GEN-LAST:event_verProd7MouseEntered

    private void verProd7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verProd7MouseExited
        verProd7.setBackground(new java.awt.Color(0, 80, 160)); 
    }//GEN-LAST:event_verProd7MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newVistaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newVistaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newVistaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newVistaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newVistaProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private java.awt.Label bttn12;
    private java.awt.Label bttn13;
    private java.awt.Label bttn14;
    private java.awt.Label bttn15;
    private java.awt.Label bttn16;
    private java.awt.Label bttn17;
    private java.awt.Label bttn2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel menu;
    private javax.swing.JTable tabla;
    private javax.swing.JPanel verProd;
    private javax.swing.JPanel verProd1;
    private javax.swing.JPanel verProd2;
    private javax.swing.JPanel verProd3;
    private javax.swing.JPanel verProd4;
    private javax.swing.JPanel verProd5;
    private javax.swing.JPanel verProd6;
    private javax.swing.JPanel verProd7;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
