/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Control.*;
import Estructuras.Empleado;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;

/**
 *
 * @author leito
 */
public class VistaEmpleado extends javax.swing.JFrame {
controladorVistaEmp control;
Empleado currentUser;
    /**
     * Creates new form VistaEmpleado
     */
    public VistaEmpleado() {
        initComponents();
        control = new controladorVistaEmp(bttnAddProd, bttnAddProv, bttnBack, bttnExit, bttnOpUser, bttnProd, bttnProv, this);
    }
    public VistaEmpleado(Empleado currentUser) {
        initComponents();
        control = new controladorVistaEmp(bttnAddProd, bttnAddProv, bttnBack, bttnExit, bttnOpUser, bttnProd, bttnProv, this);
        this.currentUser=currentUser;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bttnAddProv = new javax.swing.JButton();
        bttnAddProd = new javax.swing.JButton();
        bttnOpUser = new javax.swing.JButton();
        bttnExit = new javax.swing.JButton();
        bttnProv = new javax.swing.JButton();
        bttnProd = new javax.swing.JButton();
        bttnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Menu:");

        bttnAddProv.setText("Agregar Proveedor");
        bttnAddProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnAddProvActionPerformed(evt);
            }
        });
        bttnAddProv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bttnAddProvKeyPressed(evt);
            }
        });

        bttnAddProd.setText("Agregar Producto");
        bttnAddProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnAddProdActionPerformed(evt);
            }
        });
        bttnAddProd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bttnAddProdKeyPressed(evt);
            }
        });

        bttnOpUser.setText("Opciones de Usuario");
        bttnOpUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnOpUserActionPerformed(evt);
            }
        });
        bttnOpUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bttnOpUserKeyPressed(evt);
            }
        });

        bttnExit.setText("Salir");
        bttnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnExitActionPerformed(evt);
            }
        });
        bttnExit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bttnExitKeyPressed(evt);
            }
        });

        bttnProv.setText("Ver Proveedores");
        bttnProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnProvActionPerformed(evt);
            }
        });
        bttnProv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bttnProvKeyPressed(evt);
            }
        });

        bttnProd.setText("Ver Productos");
        bttnProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnProdActionPerformed(evt);
            }
        });
        bttnProd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bttnProdKeyPressed(evt);
            }
        });

        bttnBack.setText("Regresar");
        bttnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnBackActionPerformed(evt);
            }
        });
        bttnBack.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bttnBackKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bttnAddProv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bttnAddProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bttnOpUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bttnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bttnProv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bttnProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bttnBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addComponent(bttnProv)
                .addGap(18, 18, 18)
                .addComponent(bttnProd)
                .addGap(18, 18, 18)
                .addComponent(bttnAddProv)
                .addGap(18, 18, 18)
                .addComponent(bttnAddProd)
                .addGap(18, 18, 18)
                .addComponent(bttnOpUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(bttnBack)
                .addGap(18, 18, 18)
                .addComponent(bttnExit)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttnProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnProvActionPerformed
       control.activaVentana(new tablaProveedores(currentUser), this);
    }//GEN-LAST:event_bttnProvActionPerformed

    private void bttnProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnProdActionPerformed
       control.activaVentana(new tablaProductos(currentUser), this);
    }//GEN-LAST:event_bttnProdActionPerformed

    private void bttnAddProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnAddProvActionPerformed
       control.activaVentana(new vistaAddProv(currentUser,null,null), this);
    }//GEN-LAST:event_bttnAddProvActionPerformed

    private void bttnAddProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnAddProdActionPerformed
       control.activaVentana(new vistaAddProd(), this);
    }//GEN-LAST:event_bttnAddProdActionPerformed

    private void bttnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnBackActionPerformed
       control.activaVentana(new VistaLogin(), this);
    }//GEN-LAST:event_bttnBackActionPerformed

    private void bttnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bttnExitActionPerformed

    private void bttnProvKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bttnProvKeyPressed
                if(evt.getKeyCode()==(KeyEvent.VK_ENTER))
            this.bttnProvActionPerformed(new ActionEvent(this, 0, ""));
    }//GEN-LAST:event_bttnProvKeyPressed

    private void bttnProdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bttnProdKeyPressed
                if(evt.getKeyCode()==(KeyEvent.VK_ENTER))
            this.bttnProdActionPerformed(new ActionEvent(this, 0, ""));
    }//GEN-LAST:event_bttnProdKeyPressed

    private void bttnAddProvKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bttnAddProvKeyPressed
                if(evt.getKeyCode()==(KeyEvent.VK_ENTER))
            this.bttnAddProvActionPerformed(new ActionEvent(this, 0, ""));
    }//GEN-LAST:event_bttnAddProvKeyPressed

    private void bttnAddProdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bttnAddProdKeyPressed
        if(evt.getKeyCode()==(KeyEvent.VK_ENTER))
            this.bttnAddProdActionPerformed(new ActionEvent(this, 0, ""));
    }//GEN-LAST:event_bttnAddProdKeyPressed

    private void bttnOpUserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bttnOpUserKeyPressed
        if(evt.getKeyCode()==(KeyEvent.VK_ENTER))
            this.bttnOpUserActionPerformed(new ActionEvent(this, 0, ""));
    }//GEN-LAST:event_bttnOpUserKeyPressed

    private void bttnBackKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bttnBackKeyPressed
        if(evt.getKeyCode()==(KeyEvent.VK_ENTER))
            this.bttnBackActionPerformed(new ActionEvent(this, 0, ""));
    }//GEN-LAST:event_bttnBackKeyPressed

    private void bttnExitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bttnExitKeyPressed
        if(evt.getKeyCode()==(KeyEvent.VK_ENTER))
            System.exit(0);
    }//GEN-LAST:event_bttnExitKeyPressed

    private void bttnOpUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnOpUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttnOpUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnAddProd;
    private javax.swing.JButton bttnAddProv;
    private javax.swing.JButton bttnBack;
    private javax.swing.JButton bttnExit;
    private javax.swing.JButton bttnOpUser;
    private javax.swing.JButton bttnProd;
    private javax.swing.JButton bttnProv;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
